In [1]:
import os
import sys

# Menambahkan root directory ke sys.path
# Ini akan naik satu level dari folder 'notebooks' ke root project
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

import pandas as pd
from sqlalchemy import text
from app.database import DatabaseConnection

In [2]:
def run_sql_etl(sql_file_name, table_name):
    """
    Membaca file SQL, mengeksekusi ke database, dan mengembalikan DataFrame hasil.
    """
    engine = DatabaseConnection.get_engine()
    sql_path = os.path.join('..', 'scripts', 'sql', sql_file_name)
    
    try:
        # 1. Baca query dari file
        with open(sql_path, 'r') as f:
            query = f.read()
            
        # 2. Jalankan perintah SQL (Drop & Create)
        with engine.begin() as conn:
            # Opsional: Drop table lama jika ingin refresh data total
            conn.execute(text(f"DROP TABLE IF EXISTS transformed.{table_name}"))
            conn.execute(text(query))
            print(f"✓ ETL Success: Table transformed.{table_name} created.")

        # 3. Ambil data untuk print out ke notebook
        df = pd.read_sql(f"SELECT * FROM transformed.{table_name}", engine)
        return df

    except Exception as e:
        print(f"❌ Error saat menjalankan {sql_file_name}: {e}")
        return None

In [3]:
# Jalankan Product Specs
df_specs = run_sql_etl('/Users/naufalnashif/Desktop/de_test_danone/scripts/dm_product_specs.sql', 'dm_product_specs')
if df_specs is not None:
    display(df_specs)

✓ ETL Success: Table transformed.dm_product_specs created.

,id,product_name,price,description,rating,review_count,image_url,product_url,category,page_number,scraped_at,brand,screen_size,display_type,os,ram,storage,storage_type,processor,graphics_card
0,1,Packard 255 G2,416.99,"15.6"", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows...",2,2,/images/test-sites/e-commerce/items/cart2.png,/test-sites/e-commerce/static/product/31,computers/laptops,1,2026-02-07 16:22:05.654197+00:00,Packard,15.6,NaN,Windows,4GB,NaN,NaN,AMD E2-3800 1.3GHz,NaN
1,2,Aspire E1-510,306.99,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",3,2,/images/test-sites/e-commerce/items/cart2.png,/test-sites/e-commerce/static/product/32,computers/laptops,1,2026-02-07 16:22:05.654197+00:00,Aspire,15.6,NaN,Linux,4GB,NaN,NaN,Pentium N3520 2.16GHz,NaN
2,3,ThinkPad T540p,1178.99,"15.6"", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit",1,2,/images/test-sites/e-commerce/items/cart2.png,/test-sites/e-commerce/static/product/33,computers/laptops,1,2026-02-07 16:22:05.654197+00:00,ThinkPad,15.6,NaN,NaN,4GB,NaN,NaN,Core i5-4200M,NaN
3,4,ProBook,739.99,"14"", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit",4,8,/images/test-sites/e-commerce/items/cart2.png,/test-sites/e-commerce/static/product/34,computers/laptops,1,2026-02-07 16:22:05.654197+00:00,ProBook,14,NaN,NaN,4GB,NaN,NaN,Core i5 2.6GHz,NaN
4,5,ThinkPad X240,1311.99,"12.5"", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro...",3,12,/images/test-sites/e-commerce/items/cart2.png,/test-sites/e-commerce/static/product/35,computers/laptops,1,2026-02-07 16:22:05.654197+00:00,ThinkPad,12.5,NaN,NaN,8GB,240GB,SSD,Core i5-4300U,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,113,Lenovo ThinkPad T470,1349.23,"Lenovo ThinkPad T470, 14"" FHD IPS, Core i5-720...",1,5,/images/test-sites/e-commerce/items/cart2.png,/test-sites/e-commerce/static/product/143,computers/laptops,19,2026-02-07 16:22:05.654197+00:00,Lenovo,14,FHD,Windows,8GB,256GB,SSD,Core i5-7200U,NaN
113,114,Lenovo ThinkPad Yoga 370 Black,1362.24,"Lenovo ThinkPad Yoga 370 Black, 13.3"" FHD IPS ...",2,12,/images/test-sites/e-commerce/items/cart2.png,/test-sites/e-commerce/static/product/144,computers/laptops,19,2026-02-07 16:22:05.654197+00:00,Lenovo,13.3,FHD,Windows,8GB,256GB,SSD,Core i5-7200U,NaN
114,115,Toshiba Portege X20W-D-10V Black/Blue,1366.32,"Toshiba Portege X20W-D-10V Black/Blue, 12.5"" F...",1,11,/images/test-sites/e-commerce/items/cart2.png,/test-sites/e-commerce/static/product/145,computers/laptops,20,2026-02-07 16:22:05.654197+00:00,Toshiba,12.5,FHD,Windows,8GB,512GB,SSD,Core i7-7500U,NaN
115,116,Asus ASUSPRO B9440UA-GV0279R Gray,1381.13,"Asus ASUSPRO B9440UA-GV0279R Gray, 14"" FHD, Co...",1,4,/images/test-sites/e-commerce/items/cart2.png,/test-sites/e-commerce/static/product/146,computers/laptops,20,2026-02-07 16:22:05.654197+00:00,Asus,14,FHD,Windows,16GB,512GB,SSD,Core i7-7500U,NaN
116,117,Asus ROG Strix GL702VM-GC146T,1399.00,"Asus ROG Strix GL702VM-GC146T, 17.3"" FHD, Core...",3,10,/images/test-sites/e-commerce/items/cart2.png,/test-sites/e-commerce/static/product/147,computers/laptops,20,2026-02-07 16:22:05.654197+00:00,Asus,17.3,FHD,Windows,8GB,1TB,SSD,Core i7-7700HQ,GeForce

In [4]:
# --- Eksekusi ---
# Jalankan Brand Performance
df_brand = run_sql_etl('/Users/naufalnashif/Desktop/de_test_danone/scripts/dm_screen_size_analysis.sql', 'dm_screen_price_analysis')
if df_brand is not None:
    display(df_brand)

✓ ETL Success: Table transformed.dm_screen_price_analysis created.

  screen_size  total_products  avg_price  min_price  max_price
0        12.2               1    1212.16    1212.16    1212.16
1        12.5               6    1213.99    1033.99    1366.32
2          13               3    1313.64    1260.13    1347.78
3        13.3              13     910.90     299.00    1362.24
4        13.9               1    1199.73    1199.73    1199.73
5          14              19    1046.25     295.99    1381.13
6        15.6              64     760.60     306.99    1799.00
7        17.3              10    1236.31     410.46    1769.00